### ISSUE TITLE
是否可以记录下用户的每一笔操作

### ISSUE THREAD

**Issue by hanyou** [ding-ke/DrawingBoard#1]
我想做一个笔迹跟踪的功能，把用户画画的过程记录下来并进行播放，是否可以实现，另外您这个代码的许可是什么样的？

**Comment by ding-ke** [comment]
其实每一笔操作就是记录下来的，数据存在globObj.DATA。

**Comment by ding-ke** [comment]
> 我想做一个笔迹跟踪的功能，把用户画画的过程记录下来并进行播放，是否可以实现，另外您这个代码的许可是什么样的？

其实每一笔操作已经记录下来了，数据存在globObj.DATA。
